-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.activity_purposes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  activity_id uuid NOT NULL,
  purpose_id uuid NOT NULL,
  legal_basis text NOT NULL CHECK (legal_basis = ANY (ARRAY['consent'::text, 'contract'::text, 'legal-obligation'::text, 'legitimate-interest'::text])),
  custom_description text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT activity_purposes_pkey PRIMARY KEY (id),
  CONSTRAINT activity_purposes_activity_id_fkey FOREIGN KEY (activity_id) REFERENCES public.processing_activities(id),
  CONSTRAINT activity_purposes_purpose_id_fkey FOREIGN KEY (purpose_id) REFERENCES public.purposes(id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  action text NOT NULL,
  resource_type text NOT NULL,
  resource_id text,
  changes jsonb,
  ip_address text,
  user_agent text,
  status text CHECK (status = ANY (ARRAY['success'::text, 'failure'::text])),
  error_message text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.banner_configs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  position text NOT NULL CHECK ("position" = ANY (ARRAY['top'::text, 'bottom'::text, 'top-left'::text, 'top-right'::text, 'bottom-left'::text, 'bottom-right'::text, 'center'::text, 'center-modal'::text])),
  layout text NOT NULL CHECK (layout = ANY (ARRAY['bar'::text, 'box'::text, 'modal'::text, 'popup'::text, 'inline'::text, 'floating'::text, 'banner'::text])),
  theme jsonb NOT NULL DEFAULT '{"fontSize": 14, "boxShadow": true, "textColor": "#1f2937", "fontFamily": "system-ui, sans-serif", "borderRadius": 8, "primaryColor": "#3b82f6", "secondaryColor": "#1e40af", "backgroundColor": "#ffffff"}'::jsonb,
  title text NOT NULL,
  message text NOT NULL,
  privacy_policy_url text,
  privacy_policy_text text DEFAULT 'Privacy Policy'::text,
  accept_button jsonb NOT NULL DEFAULT '{"text": "Accept All", "fontSize": 14, "textColor": "#ffffff", "fontWeight": "semibold", "borderRadius": 6, "backgroundColor": "#3b82f6"}'::jsonb,
  reject_button jsonb DEFAULT '{"text": "Reject All", "fontSize": 14, "textColor": "#3b82f6", "fontWeight": "medium", "borderColor": "#3b82f6", "borderRadius": 6, "backgroundColor": "#ffffff"}'::jsonb,
  settings_button jsonb DEFAULT '{"text": "Cookie Settings", "fontSize": 14, "textColor": "#1f2937", "fontWeight": "normal", "borderRadius": 6, "backgroundColor": "#f3f4f6"}'::jsonb,
  show_reject_button boolean DEFAULT true,
  show_settings_button boolean DEFAULT true,
  auto_show boolean DEFAULT true,
  show_after_delay integer DEFAULT 0 CHECK (show_after_delay >= 0 AND show_after_delay <= 60000),
  respect_dnt boolean DEFAULT false,
  block_content boolean DEFAULT false,
  custom_css text,
  custom_js text,
  z_index integer DEFAULT 9999 CHECK (z_index >= 1 AND z_index <= 999999),
  is_active boolean DEFAULT true,
  is_default boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  cookie_policy_url text,
  cookie_policy_text text DEFAULT 'Cookie Policy'::text,
  terms_url text,
  terms_text text DEFAULT 'Terms & Conditions'::text,
  CONSTRAINT banner_configs_pkey PRIMARY KEY (id),
  CONSTRAINT banner_configs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.banner_versions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  banner_id uuid NOT NULL,
  user_id uuid NOT NULL,
  version integer NOT NULL,
  config jsonb NOT NULL,
  change_description text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT banner_versions_pkey PRIMARY KEY (id),
  CONSTRAINT banner_versions_banner_id_fkey FOREIGN KEY (banner_id) REFERENCES public.banner_configs(id),
  CONSTRAINT banner_versions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.blog_posts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  slug text NOT NULL UNIQUE,
  excerpt text NOT NULL,
  content text NOT NULL,
  category text NOT NULL DEFAULT 'General'::text,
  tags ARRAY DEFAULT '{}'::text[],
  featured_image text,
  author_name text NOT NULL,
  author_email text NOT NULL,
  published boolean DEFAULT false,
  published_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  reading_time integer DEFAULT 5,
  views integer DEFAULT 0,
  meta_title text,
  meta_description text,
  seo_keywords ARRAY,
  CONSTRAINT blog_posts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.consent_analytics (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  date date NOT NULL,
  total_visitors integer DEFAULT 0,
  consents_given integer DEFAULT 0,
  consents_denied integer DEFAULT 0,
  consents_partial integer DEFAULT 0,
  consents_revoked integer DEFAULT 0,
  category_analytics jsonb DEFAULT '{}'::jsonb,
  device_breakdown jsonb DEFAULT '{}'::jsonb,
  geo_breakdown jsonb DEFAULT '{}'::jsonb,
  browser_breakdown jsonb DEFAULT '{}'::jsonb,
  consent_rate numeric,
  average_time_to_consent integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT consent_analytics_pkey PRIMARY KEY (id),
  CONSTRAINT consent_analytics_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.consent_history (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  visitor_id text NOT NULL,
  widget_id text NOT NULL,
  activity_id uuid NOT NULL,
  previous_status text CHECK (previous_status = ANY (ARRAY['accepted'::text, 'rejected'::text, 'withdrawn'::text, NULL::text])),
  new_status text NOT NULL CHECK (new_status = ANY (ARRAY['accepted'::text, 'rejected'::text, 'withdrawn'::text])),
  change_reason text,
  change_source text DEFAULT 'privacy_centre'::text CHECK (change_source = ANY (ARRAY['privacy_centre'::text, 'widget'::text, 'admin'::text, 'system'::text])),
  ip_address text,
  user_agent text,
  device_type text,
  language text,
  consent_version text DEFAULT '1.0'::text,
  changed_at timestamp with time zone DEFAULT now(),
  CONSTRAINT consent_history_pkey PRIMARY KEY (id),
  CONSTRAINT consent_history_activity_id_fkey FOREIGN KEY (activity_id) REFERENCES public.processing_activities(id)
);
CREATE TABLE public.consent_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  consent_id text NOT NULL,
  visitor_token text NOT NULL,
  consent_type text NOT NULL CHECK (consent_type = ANY (ARRAY['cookie'::text, 'dpdpa'::text, 'gdpr'::text])),
  status text NOT NULL CHECK (status = ANY (ARRAY['accepted'::text, 'rejected'::text, 'partial'::text, 'revoked'::text, 'updated'::text])),
  categories jsonb DEFAULT '[]'::jsonb,
  cookies_accepted ARRAY,
  cookies_rejected ARRAY,
  device_info jsonb,
  geo_location jsonb,
  ip_address text,
  user_agent text,
  referrer text,
  page_url text,
  language text,
  browser_fingerprint text,
  consent_method text CHECK (consent_method = ANY (ARRAY['banner'::text, 'settings_modal'::text, 'api'::text, 'implicit'::text])),
  widget_version text,
  tcf_string text,
  created_at timestamp with time zone DEFAULT now(),
  widget_id character varying,
  CONSTRAINT consent_logs_pkey PRIMARY KEY (id),
  CONSTRAINT consent_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT fk_consent_logs_widget FOREIGN KEY (widget_id) REFERENCES public.widget_configs(widget_id)
);
CREATE TABLE public.consent_receipts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  consent_id text NOT NULL UNIQUE,
  visitor_email text,
  receipt_number text NOT NULL UNIQUE,
  consent_data jsonb NOT NULL,
  receipt_html text,
  receipt_pdf_url text,
  sent_at timestamp with time zone,
  viewed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT consent_receipts_pkey PRIMARY KEY (id),
  CONSTRAINT consent_receipts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.consent_records (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  consent_id text NOT NULL UNIQUE,
  consent_type text NOT NULL CHECK (consent_type = ANY (ARRAY['cookie'::text, 'dpdpa'::text])),
  status text NOT NULL CHECK (status = ANY (ARRAY['accepted'::text, 'rejected'::text, 'partial'::text, 'revoked'::text])),
  categories jsonb DEFAULT '{}'::jsonb,
  device_type text NOT NULL CHECK (device_type = ANY (ARRAY['Desktop'::text, 'Mobile'::text, 'Tablet'::text])),
  ip_address text,
  user_agent text,
  language text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  widget_id character varying,
  CONSTRAINT consent_records_pkey PRIMARY KEY (id),
  CONSTRAINT consent_records_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT fk_consent_records_widget FOREIGN KEY (widget_id) REFERENCES public.widget_configs(widget_id)
);
CREATE TABLE public.cookie_banners (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  website_url text NOT NULL,
  banner_style text NOT NULL CHECK (banner_style = ANY (ARRAY['minimal'::text, 'detailed'::text, 'floating'::text, 'sidebar'::text])),
  position text DEFAULT 'bottom'::text CHECK ("position" = ANY (ARRAY['top'::text, 'bottom'::text, 'center'::text, 'bottom-left'::text, 'bottom-right'::text])),
  primary_color text DEFAULT '#3b82f6'::text,
  text_color text DEFAULT '#1f2937'::text,
  background_color text DEFAULT '#ffffff'::text,
  title text NOT NULL,
  message text NOT NULL,
  accept_text text DEFAULT 'Accept All'::text,
  reject_text text DEFAULT 'Reject All'::text,
  settings_text text DEFAULT 'Cookie Settings'::text,
  language text DEFAULT 'en'::text,
  categories jsonb DEFAULT '["necessary"]'::jsonb,
  industry text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cookie_banners_pkey PRIMARY KEY (id),
  CONSTRAINT cookie_banners_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.cookie_categories (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  category_id text NOT NULL,
  name text NOT NULL,
  description text NOT NULL,
  is_required boolean DEFAULT false,
  display_order integer DEFAULT 0,
  icon text,
  color text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cookie_categories_pkey PRIMARY KEY (id),
  CONSTRAINT cookie_categories_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.cookie_compliance_checks (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  check_id text NOT NULL UNIQUE,
  check_type text CHECK (check_type = ANY (ARRAY['gdpr'::text, 'dpdpa'::text, 'ccpa'::text, 'eprivacy'::text])),
  check_status text CHECK (check_status = ANY (ARRAY['pass'::text, 'fail'::text, 'warning'::text, 'info'::text])),
  issues_found jsonb DEFAULT '[]'::jsonb,
  recommendations jsonb DEFAULT '[]'::jsonb,
  compliance_score integer CHECK (compliance_score >= 0 AND compliance_score <= 100),
  checked_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cookie_compliance_checks_pkey PRIMARY KEY (id),
  CONSTRAINT cookie_compliance_checks_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.cookie_policies (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  company_name text NOT NULL,
  website_url text NOT NULL,
  contact_email text NOT NULL,
  company_address text,
  policy_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  scan_id uuid,
  version text DEFAULT '1.0'::text,
  is_published boolean DEFAULT false,
  published_at timestamp with time zone,
  published_url text,
  custom_sections jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cookie_policies_pkey PRIMARY KEY (id),
  CONSTRAINT cookie_policies_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT cookie_policies_scan_id_fkey FOREIGN KEY (scan_id) REFERENCES public.cookie_scans(id)
);
CREATE TABLE public.cookie_scan_history (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  scan_id text NOT NULL UNIQUE,
  website_url text NOT NULL,
  scan_status text CHECK (scan_status = ANY (ARRAY['pending'::text, 'running'::text, 'completed'::text, 'failed'::text])),
  scan_depth text CHECK (scan_depth = ANY (ARRAY['shallow'::text, 'medium'::text, 'deep'::text])),
  pages_scanned integer DEFAULT 0,
  cookies_found integer DEFAULT 0,
  new_cookies integer DEFAULT 0,
  changed_cookies integer DEFAULT 0,
  removed_cookies integer DEFAULT 0,
  scan_duration integer,
  error_message text,
  cookies_data jsonb DEFAULT '[]'::jsonb,
  classification jsonb DEFAULT '{}'::jsonb,
  recommendations jsonb DEFAULT '[]'::jsonb,
  compliance_score integer CHECK (compliance_score >= 0 AND compliance_score <= 100),
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cookie_scan_history_pkey PRIMARY KEY (id),
  CONSTRAINT cookie_scan_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.cookie_scans (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  website_url text NOT NULL,
  scan_date timestamp with time zone DEFAULT now(),
  cookies_found jsonb DEFAULT '[]'::jsonb,
  classification jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cookie_scans_pkey PRIMARY KEY (id),
  CONSTRAINT cookie_scans_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.cookies (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  name text NOT NULL,
  domain text NOT NULL,
  category text NOT NULL CHECK (category = ANY (ARRAY['necessary'::text, 'functional'::text, 'analytics'::text, 'advertising'::text, 'social'::text, 'preferences'::text])),
  purpose text NOT NULL,
  description text,
  provider text,
  provider_url text,
  expiry text NOT NULL,
  expiry_days integer,
  type text CHECK (type = ANY (ARRAY['http'::text, 'javascript'::text, 'pixel'::text, 'server'::text])),
  is_third_party boolean DEFAULT false,
  data_collected ARRAY,
  legal_basis text CHECK (legal_basis = ANY (ARRAY['consent'::text, 'legitimate_interest'::text, 'contract'::text, 'legal_obligation'::text])),
  dpo_contact text,
  is_active boolean DEFAULT true,
  last_scanned_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cookies_pkey PRIMARY KEY (id),
  CONSTRAINT cookies_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.data_recipients (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  activity_id uuid NOT NULL,
  recipient_name text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT data_recipients_pkey PRIMARY KEY (id),
  CONSTRAINT data_recipients_activity_id_fkey FOREIGN KEY (activity_id) REFERENCES public.processing_activities(id)
);
CREATE TABLE public.data_sources (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  activity_id uuid NOT NULL,
  source_name text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT data_sources_pkey PRIMARY KEY (id),
  CONSTRAINT data_sources_activity_id_fkey FOREIGN KEY (activity_id) REFERENCES public.processing_activities(id)
);
CREATE TABLE public.dpdp_rights_requests (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  visitor_id text NOT NULL,
  visitor_email text NOT NULL,
  visitor_email_hash text NOT NULL,
  visitor_name text,
  visitor_phone text,
  widget_id text NOT NULL,
  request_type text NOT NULL CHECK (request_type = ANY (ARRAY['access'::text, 'correction'::text, 'erasure'::text, 'grievance'::text, 'nomination'::text])),
  request_title text NOT NULL,
  request_description text NOT NULL,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'under_review'::text, 'in_progress'::text, 'completed'::text, 'rejected'::text, 'cancelled'::text])),
  admin_notes text,
  response_message text,
  rejection_reason text,
  attachments jsonb DEFAULT '[]'::jsonb,
  response_attachments jsonb DEFAULT '[]'::jsonb,
  is_verified boolean DEFAULT false,
  verification_token text,
  verification_code text,
  verified_at timestamp with time zone,
  ip_address text,
  user_agent text,
  device_type text,
  language text DEFAULT 'en'::text,
  due_date timestamp with time zone,
  completed_at timestamp with time zone,
  resolved_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dpdp_rights_requests_pkey PRIMARY KEY (id),
  CONSTRAINT dpdp_rights_requests_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES public.users(id)
);
CREATE TABLE public.dpdpa_consent_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  widget_id text NOT NULL,
  visitor_id text NOT NULL,
  rule_id text,
  rule_name text,
  consent_status text NOT NULL CHECK (consent_status = ANY (ARRAY['accepted'::text, 'rejected'::text, 'partial'::text])),
  accepted_activities ARRAY DEFAULT '{}'::text[],
  rejected_activities ARRAY DEFAULT '{}'::text[],
  consented_at timestamp with time zone NOT NULL DEFAULT now(),
  user_agent text,
  device_type text CHECK (device_type = ANY (ARRAY['Desktop'::text, 'Mobile'::text, 'Tablet'::text, 'Unknown'::text])),
  country text,
  language text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  consent_record_id uuid,
  CONSTRAINT dpdpa_consent_events_pkey PRIMARY KEY (id),
  CONSTRAINT fk_widget FOREIGN KEY (widget_id) REFERENCES public.dpdpa_widget_configs(widget_id),
  CONSTRAINT dpdpa_consent_events_consent_record_id_fkey FOREIGN KEY (consent_record_id) REFERENCES public.dpdpa_consent_records(id)
);
CREATE TABLE public.dpdpa_consent_records (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  widget_id text NOT NULL,
  visitor_id text NOT NULL,
  consent_status text NOT NULL CHECK (consent_status = ANY (ARRAY['accepted'::text, 'rejected'::text, 'partial'::text, 'revoked'::text])),
  consented_activities ARRAY DEFAULT '{}'::uuid[],
  rejected_activities ARRAY DEFAULT '{}'::uuid[],
  activity_consents jsonb DEFAULT '{}'::jsonb,
  ip_address text,
  user_agent text,
  device_type text CHECK (device_type = ANY (ARRAY['Desktop'::text, 'Mobile'::text, 'Tablet'::text, 'Unknown'::text])),
  browser text,
  os text,
  country text,
  language text,
  referrer text,
  consent_given_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  consent_expires_at timestamp with time zone,
  consent_version text DEFAULT '1.0'::text,
  widget_version text,
  created_at timestamp with time zone DEFAULT now(),
  country_code character varying,
  region character varying,
  revoked_at timestamp with time zone,
  revocation_reason text,
  current_url text,
  page_title character varying,
  consent_details jsonb DEFAULT '{}'::jsonb,
  consent_id character varying NOT NULL,
  privacy_notice_version character varying,
  visitor_email_hash character varying,
  visitor_email text,
  CONSTRAINT dpdpa_consent_records_pkey PRIMARY KEY (id)
);
CREATE TABLE public.dpdpa_grievances (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  widget_id text NOT NULL,
  email text,
  name text,
  message text NOT NULL,
  type text DEFAULT 'general'::text CHECK (type = ANY (ARRAY['access'::text, 'correction'::text, 'deletion'::text, 'withdrawal'::text, 'general'::text, 'complaint'::text])),
  status text DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'in-progress'::text, 'resolved'::text, 'closed'::text])),
  admin_notes text,
  resolved_at timestamp with time zone,
  resolved_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  first_response_at timestamp with time zone,
  internal_notes text,
  attachments jsonb DEFAULT '[]'::jsonb,
  compliance_status character varying DEFAULT 'pending'::character varying CHECK (compliance_status::text = ANY (ARRAY['pending'::character varying, 'compliant'::character varying, 'overdue'::character varying, 'breached'::character varying]::text[])),
  escalation_reason text,
  CONSTRAINT dpdpa_grievances_pkey PRIMARY KEY (id),
  CONSTRAINT dpdpa_grievances_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES public.users(id)
);
CREATE TABLE public.dpdpa_rule_match_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  widget_id text NOT NULL,
  visitor_id text NOT NULL,
  rule_id text NOT NULL,
  rule_name text NOT NULL,
  url_pattern text NOT NULL,
  page_url text NOT NULL,
  matched_at timestamp with time zone NOT NULL DEFAULT now(),
  trigger_type text NOT NULL CHECK (trigger_type = ANY (ARRAY['onPageLoad'::text, 'onClick'::text, 'onFormSubmit'::text, 'onScroll'::text])),
  user_agent text,
  device_type text CHECK (device_type = ANY (ARRAY['Desktop'::text, 'Mobile'::text, 'Tablet'::text, 'Unknown'::text])),
  country text,
  language text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT dpdpa_rule_match_events_pkey PRIMARY KEY (id),
  CONSTRAINT fk_widget FOREIGN KEY (widget_id) REFERENCES public.dpdpa_widget_configs(widget_id)
);
CREATE TABLE public.dpdpa_widget_configs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  widget_id text NOT NULL UNIQUE,
  name text NOT NULL,
  domain text NOT NULL,
  position text DEFAULT 'bottom-right'::text CHECK ("position" = ANY (ARRAY['top'::text, 'bottom'::text, 'center'::text, 'bottom-left'::text, 'bottom-right'::text, 'modal'::text])),
  layout text DEFAULT 'modal'::text CHECK (layout = ANY (ARRAY['modal'::text, 'slide-in'::text, 'banner'::text])),
  theme jsonb DEFAULT '{"fontSize": 14, "boxShadow": true, "textColor": "#1f2937", "fontFamily": "system-ui, sans-serif", "borderRadius": 12, "primaryColor": "#3b82f6", "secondaryColor": "#1e40af", "backgroundColor": "#ffffff"}'::jsonb,
  title text DEFAULT 'Your Data Privacy Rights'::text,
  message text DEFAULT 'We process your personal data with your consent. Please review the activities below and choose your preferences.'::text,
  accept_button_text text DEFAULT 'Accept All'::text,
  reject_button_text text DEFAULT 'Reject All'::text,
  customize_button_text text DEFAULT 'Manage Preferences'::text,
  selected_activities ARRAY DEFAULT '{}'::uuid[],
  auto_show boolean DEFAULT true,
  show_after_delay integer DEFAULT 1000,
  consent_duration integer DEFAULT 365,
  respect_dnt boolean DEFAULT false,
  require_explicit_consent boolean DEFAULT true,
  show_data_subjects_rights boolean DEFAULT true,
  language text DEFAULT 'en'::text,
  custom_translations jsonb DEFAULT '{}'::jsonb,
  enable_analytics boolean DEFAULT true,
  enable_audit_log boolean DEFAULT true,
  show_branding boolean DEFAULT true,
  custom_css text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  supported_languages ARRAY DEFAULT ARRAY['en'::text, 'hi'::text, 'pa'::text, 'te'::text, 'ta'::text],
  privacy_notice_version character varying,
  privacy_notice_last_updated timestamp with time zone,
  requires_reconsent boolean DEFAULT false,
  display_rules jsonb DEFAULT '[]'::jsonb,
  otp_expiration_minutes integer DEFAULT 10 CHECK (otp_expiration_minutes >= 1 AND otp_expiration_minutes <= 60),
  CONSTRAINT dpdpa_widget_configs_pkey PRIMARY KEY (id),
  CONSTRAINT dpdpa_widget_configs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.email_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  template_name text NOT NULL,
  recipient_email text NOT NULL,
  subject text NOT NULL,
  status text NOT NULL CHECK (status = ANY (ARRAY['sent'::text, 'failed'::text, 'pending'::text])),
  error_message text,
  sent_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT email_logs_pkey PRIMARY KEY (id),
  CONSTRAINT email_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.email_templates (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  template_name text NOT NULL UNIQUE,
  subject text NOT NULL,
  body text NOT NULL,
  variables jsonb DEFAULT '[]'::jsonb,
  description text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT email_templates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.email_verification_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  widget_id text NOT NULL,
  visitor_id text NOT NULL,
  event_type text NOT NULL CHECK (event_type = ANY (ARRAY['otp_sent'::text, 'otp_verified'::text, 'otp_failed'::text, 'otp_skipped'::text, 'rate_limited'::text])),
  email_hash text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT email_verification_events_pkey PRIMARY KEY (id),
  CONSTRAINT fk_email_verification_events_widget FOREIGN KEY (widget_id) REFERENCES public.dpdpa_widget_configs(widget_id)
);
CREATE TABLE public.email_verification_otps (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email character varying NOT NULL,
  email_hash character varying NOT NULL,
  otp_code character varying NOT NULL,
  visitor_id character varying NOT NULL,
  widget_id character varying NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  verified boolean DEFAULT false,
  verified_at timestamp with time zone,
  attempts integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT email_verification_otps_pkey PRIMARY KEY (id),
  CONSTRAINT email_verification_otps_widget_id_fkey FOREIGN KEY (widget_id) REFERENCES public.dpdpa_widget_configs(widget_id)
);
CREATE TABLE public.processing_activities (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  activity_name text NOT NULL,
  industry text NOT NULL,
  data_attributes ARRAY NOT NULL DEFAULT '{}'::text[],
  purpose text,
  retention_period text,
  data_processors jsonb DEFAULT '[]'::jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  legal_basis text CHECK (legal_basis = ANY (ARRAY['consent'::text, 'contract'::text, 'legal-obligation'::text, 'legitimate-interest'::text])),
  CONSTRAINT processing_activities_pkey PRIMARY KEY (id),
  CONSTRAINT processing_activities_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.purpose_data_categories (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  activity_purpose_id uuid NOT NULL,
  category_name text NOT NULL,
  retention_period text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT purpose_data_categories_pkey PRIMARY KEY (id),
  CONSTRAINT purpose_data_categories_activity_purpose_id_fkey FOREIGN KEY (activity_purpose_id) REFERENCES public.activity_purposes(id)
);
CREATE TABLE public.purposes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  purpose_name character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  description text,
  data_category character varying,
  retention_period character varying,
  is_predefined boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT purposes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.subscriptions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  plan text NOT NULL CHECK (plan = ANY (ARRAY['small'::text, 'medium'::text, 'enterprise'::text])),
  status text NOT NULL CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'cancelled'::text])),
  amount numeric NOT NULL,
  currency text DEFAULT 'INR'::text,
  billing_cycle text DEFAULT 'monthly'::text CHECK (billing_cycle = ANY (ARRAY['monthly'::text, 'yearly'::text])),
  payment_provider text DEFAULT 'razorpay'::text CHECK (payment_provider = ANY (ARRAY['razorpay'::text, 'stripe'::text])),
  payment_id text,
  start_date timestamp with time zone DEFAULT now(),
  end_date timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_trial boolean DEFAULT false,
  trial_end timestamp with time zone,
  CONSTRAINT subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL,
  email text NOT NULL UNIQUE,
  full_name text,
  company_name text,
  phone text,
  website text,
  avatar_url text,
  auth_provider text NOT NULL CHECK (auth_provider = ANY (ARRAY['email'::text, 'google'::text, 'twitter'::text, 'apple'::text])),
  subscription_plan text CHECK (subscription_plan = ANY (ARRAY['small'::text, 'medium'::text, 'enterprise'::text])),
  subscription_status text CHECK (subscription_status = ANY (ARRAY['active'::text, 'inactive'::text, 'cancelled'::text])),
  onboarding_completed boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  demo_account boolean DEFAULT false,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.visitor_consent_preferences (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  visitor_id text NOT NULL,
  widget_id text NOT NULL,
  activity_id uuid NOT NULL,
  consent_status text NOT NULL CHECK (consent_status = ANY (ARRAY['accepted'::text, 'rejected'::text, 'withdrawn'::text])),
  ip_address text,
  user_agent text,
  device_type text CHECK (device_type = ANY (ARRAY['Desktop'::text, 'Mobile'::text, 'Tablet'::text, 'Unknown'::text])),
  language text,
  consent_given_at timestamp with time zone DEFAULT now(),
  last_updated timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone,
  consent_version text DEFAULT '1.0'::text,
  created_at timestamp with time zone DEFAULT now(),
  visitor_email_hash character varying,
  visitor_email text,
  CONSTRAINT visitor_consent_preferences_pkey PRIMARY KEY (id),
  CONSTRAINT visitor_consent_preferences_activity_id_fkey FOREIGN KEY (activity_id) REFERENCES public.processing_activities(id)
);
CREATE TABLE public.widget_configs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  widget_id text NOT NULL UNIQUE,
  domain text NOT NULL,
  categories ARRAY DEFAULT '{necessary}'::text[],
  behavior text DEFAULT 'explicit'::text CHECK (behavior = ANY (ARRAY['implicit'::text, 'explicit'::text, 'optout'::text])),
  consent_duration integer DEFAULT 365,
  show_branding_link boolean DEFAULT true,
  block_scripts boolean DEFAULT true,
  respect_dnt boolean DEFAULT false,
  gdpr_applies boolean DEFAULT true,
  auto_block ARRAY DEFAULT '{}'::text[],
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  banner_template_id uuid,
  language text DEFAULT 'en'::text,
  supported_languages ARRAY DEFAULT ARRAY['en'::text, 'hi'::text, 'es'::text, 'fr'::text, 'de'::text],
  auto_show boolean DEFAULT true,
  show_after_delay integer DEFAULT 0,
  theme jsonb,
  position text DEFAULT 'bottom'::text CHECK ("position" = ANY (ARRAY['top'::text, 'bottom'::text, 'top-left'::text, 'top-right'::text, 'bottom-left'::text, 'bottom-right'::text, 'center'::text])),
  layout text DEFAULT 'bar'::text CHECK (layout = ANY (ARRAY['bar'::text, 'box'::text, 'modal'::text, 'banner'::text])),
  banner_content jsonb DEFAULT '{"title": "🍪 We value your privacy", "message": "We use cookies to enhance your browsing experience, serve personalized content, and analyze our traffic. By clicking \"Accept All\", you consent to our use of cookies.", "acceptButtonText": "Accept All", "rejectButtonText": "Reject All", "settingsButtonText": "Cookie Settings"}'::jsonb,
  name text DEFAULT 'My Cookie Widget'::text,
  is_active boolean DEFAULT true,
  CONSTRAINT widget_configs_pkey PRIMARY KEY (id),
  CONSTRAINT widget_configs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT widget_configs_banner_template_id_fkey FOREIGN KEY (banner_template_id) REFERENCES public.banner_configs(id)
);
CREATE TABLE public.widget_performance_metrics (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  widget_id uuid,
  date date NOT NULL,
  impressions integer DEFAULT 0,
  interactions integer DEFAULT 0,
  load_time_avg integer,
  load_time_p95 integer,
  error_count integer DEFAULT 0,
  bounce_rate numeric,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT widget_performance_metrics_pkey PRIMARY KEY (id),
  CONSTRAINT widget_performance_metrics_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT widget_performance_metrics_widget_id_fkey FOREIGN KEY (widget_id) REFERENCES public.widget_configs(id)
);
CREATE TABLE public.widget_translations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  widget_id uuid,
  language_code text NOT NULL CHECK (language_code ~ '^[a-z]{2}(-[A-Z]{2})?$'::text),
  title text NOT NULL,
  message text NOT NULL,
  accept_text text DEFAULT 'Accept All'::text,
  reject_text text DEFAULT 'Reject All'::text,
  settings_text text DEFAULT 'Cookie Settings'::text,
  save_text text DEFAULT 'Save Preferences'::text,
  close_text text DEFAULT 'Close'::text,
  category_translations jsonb DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT widget_translations_pkey PRIMARY KEY (id),
  CONSTRAINT widget_translations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT widget_translations_widget_id_fkey FOREIGN KEY (widget_id) REFERENCES public.widget_configs(id)
);