import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface ComplianceReportData {
  reportMetadata: {
    generatedAt: string;
    generatedBy: string;
    companyName?: string;
    reportPeriod: string;
  };
  summary: {
    totalConsents: number;
    acceptedCount: number;
    rejectedCount: number;
    partialCount: number;
    revokedCount: number;
    acceptanceRate: number;
    uniqueVisitors: number;
  };
  activities: Array<{
    name: string;
    purpose: string;
    acceptanceRate: number;
    totalResponses: number;
  }>;
  recentConsents: Array<{
    timestamp: string;
    status: string;
    deviceType: string;
    country: string;
    ipAddress?: string;
  }>;
}

export class DPDPAReportGenerator {
  private doc: jsPDF;
  private pageHeight: number;
  private currentY: number;
  private margin: number = 20;

  constructor() {
    this.doc = new jsPDF();
    this.pageHeight = this.doc.internal.pageSize.height;
    this.currentY = this.margin;
  }

  private checkPageBreak(requiredHeight: number = 20): void {
    if (this.currentY + requiredHeight > this.pageHeight - this.margin) {
      this.doc.addPage();
      this.currentY = this.margin;
    }
  }

  private addTitle(title: string): void {
    this.doc.setFontSize(22);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setTextColor(37, 99, 235); // Blue-600
    this.doc.text(title, this.margin, this.currentY);
    this.currentY += 15;
  }

  private addSection(title: string): void {
    this.checkPageBreak(15);
    this.doc.setFontSize(14);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setTextColor(31, 41, 55); // Gray-800
    this.doc.text(title, this.margin, this.currentY);
    this.currentY += 8;
  }

  private addText(text: string, fontSize: number = 10, style: 'normal' | 'bold' = 'normal'): void {
    this.doc.setFontSize(fontSize);
    this.doc.setFont('helvetica', style);
    this.doc.setTextColor(75, 85, 99); // Gray-600
    this.doc.text(text, this.margin, this.currentY);
    this.currentY += 6;
  }

  private addKeyValue(key: string, value: string, color?: string): void {
    const valueStartX = 100;
    this.doc.setFontSize(10);
    
    // Key
    this.doc.setFont('helvetica', 'bold');
    this.doc.setTextColor(55, 65, 81); // Gray-700
    this.doc.text(key + ':', this.margin, this.currentY);
    
    // Value
    this.doc.setFont('helvetica', 'normal');
    if (color) {
      const colors: Record<string, [number, number, number]> = {
        green: [34, 197, 94],
        red: [239, 68, 68],
        amber: [245, 158, 11],
        blue: [59, 130, 246],
      };
      const rgb = colors[color] || [75, 85, 99];
      this.doc.setTextColor(rgb[0], rgb[1], rgb[2]);
    } else {
      this.doc.setTextColor(75, 85, 99);
    }
    this.doc.text(value, valueStartX, this.currentY);
    
    this.currentY += 7;
  }

  private addSpacer(height: number = 10): void {
    this.currentY += height;
  }

  public generateReport(data: ComplianceReportData): jsPDF {
    // Header
    this.addTitle('DPDPA Consent Compliance Report');
    this.addSpacer(5);
    
    // Horizontal line
    this.doc.setDrawColor(229, 231, 235); // Gray-200
    this.doc.setLineWidth(0.5);
    this.doc.line(this.margin, this.currentY, this.doc.internal.pageSize.width - this.margin, this.currentY);
    this.addSpacer(10);

    // Report Metadata
    this.addSection('Report Information');
    this.addKeyValue('Generated At', new Date(data.reportMetadata.generatedAt).toLocaleString());
    this.addKeyValue('Generated By', data.reportMetadata.generatedBy);
    if (data.reportMetadata.companyName) {
      this.addKeyValue('Company', data.reportMetadata.companyName);
    }
    this.addKeyValue('Report Period', data.reportMetadata.reportPeriod);
    this.addSpacer(15);

    // Summary Statistics
    this.addSection('Consent Statistics Summary');
    this.addKeyValue('Total Consents', data.summary.totalConsents.toLocaleString(), 'blue');
    this.addKeyValue('Acceptance Rate', data.summary.acceptanceRate.toFixed(1) + '%', 'green');
    this.addKeyValue('Accepted', data.summary.acceptedCount.toLocaleString(), 'green');
    this.addKeyValue('Rejected', data.summary.rejectedCount.toLocaleString(), 'red');
    this.addKeyValue('Partial Consent', data.summary.partialCount.toLocaleString(), 'amber');
    this.addKeyValue('Revoked', data.summary.revokedCount.toLocaleString(), 'red');
    this.addKeyValue('Unique Visitors', data.summary.uniqueVisitors.toLocaleString(), 'blue');
    this.addSpacer(15);

    // Activity Performance
    this.checkPageBreak(60);
    this.addSection('Processing Activities Performance');
    this.addSpacer(5);

    if (data.activities.length > 0) {
      const activityTableData = data.activities.map(activity => [
        activity.name,
        activity.purpose.substring(0, 50) + (activity.purpose.length > 50 ? '...' : ''),
        activity.acceptanceRate.toFixed(1) + '%',
        activity.totalResponses.toString(),
      ]);

      autoTable(this.doc, {
        startY: this.currentY,
        head: [['Activity', 'Purpose', 'Acceptance Rate', 'Responses']],
        body: activityTableData,
        theme: 'grid',
        headStyles: {
          fillColor: [37, 99, 235], // Blue-600
          textColor: [255, 255, 255],
          fontStyle: 'bold',
        },
        alternateRowStyles: {
          fillColor: [249, 250, 251], // Gray-50
        },
        margin: { left: this.margin, right: this.margin },
        styles: {
          fontSize: 9,
          cellPadding: 4,
        },
      });

      this.currentY = (this.doc as any).lastAutoTable.finalY + 15;
    } else {
      this.addText('No activity data available', 10, 'normal');
      this.addSpacer(15);
    }

    // Recent Consent Records
    this.checkPageBreak(60);
    this.addSection('Recent Consent Records');
    this.addSpacer(5);

    if (data.recentConsents.length > 0) {
      const consentTableData = data.recentConsents.map(consent => [
        new Date(consent.timestamp).toLocaleString(),
        consent.status.toUpperCase(),
        consent.deviceType || 'N/A',
        consent.country || 'N/A',
        consent.ipAddress || 'N/A',
      ]);

      autoTable(this.doc, {
        startY: this.currentY,
        head: [['Timestamp', 'Status', 'Device', 'Country', 'IP Address']],
        body: consentTableData,
        theme: 'grid',
        headStyles: {
          fillColor: [37, 99, 235],
          textColor: [255, 255, 255],
          fontStyle: 'bold',
        },
        columnStyles: {
          0: { cellWidth: 40 },
          1: { cellWidth: 25 },
          2: { cellWidth: 25 },
          3: { cellWidth: 25 },
          4: { cellWidth: 35 },
        },
        alternateRowStyles: {
          fillColor: [249, 250, 251],
        },
        margin: { left: this.margin, right: this.margin },
        styles: {
          fontSize: 8,
          cellPadding: 3,
        },
      });

      this.currentY = (this.doc as any).lastAutoTable.finalY + 15;
    } else {
      this.addText('No recent consent records', 10, 'normal');
      this.addSpacer(15);
    }

    // Compliance Statement
    this.checkPageBreak(40);
    this.addSection('Compliance Statement');
    this.addText('This report is generated in accordance with the Digital Personal Data Protection Act, 2023 (DPDPA).', 9);
    this.addText('All consent records are maintained with proper audit trails as required by law.', 9);
    this.addSpacer(5);
    this.addText('The data presented in this report reflects the consent decisions made by visitors during the specified period.', 9);
    this.addSpacer(15);

    // Footer on last page
    const totalPages = this.doc.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      this.doc.setPage(i);
      this.doc.setFontSize(8);
      this.doc.setTextColor(156, 163, 175); // Gray-400
      this.doc.text(
        `Page ${i} of ${totalPages}`,
        this.doc.internal.pageSize.width / 2,
        this.pageHeight - 10,
        { align: 'center' }
      );
      this.doc.text(
        'Consently - DPDPA Compliance Platform',
        this.doc.internal.pageSize.width / 2,
        this.pageHeight - 5,
        { align: 'center' }
      );
    }

    return this.doc;
  }

  public save(filename: string): void {
    this.doc.save(filename);
  }

  public output(): Blob {
    return this.doc.output('blob');
  }
}
