export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          avatar_url: string | null;
          auth_provider: 'email' | 'google' | 'twitter' | 'apple';
          subscription_plan: 'small' | 'medium' | 'enterprise' | null;
          subscription_status: 'active' | 'inactive' | 'cancelled' | null;
          onboarding_completed: boolean;
          demo_account: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string | null;
          avatar_url?: string | null;
          auth_provider: 'email' | 'google' | 'twitter' | 'apple';
          subscription_plan?: 'small' | 'medium' | 'enterprise' | null;
          subscription_status?: 'active' | 'inactive' | 'cancelled' | null;
          onboarding_completed?: boolean;
          demo_account?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string | null;
          avatar_url?: string | null;
          auth_provider?: 'email' | 'google' | 'twitter' | 'apple';
          subscription_plan?: 'small' | 'medium' | 'enterprise' | null;
          subscription_status?: 'active' | 'inactive' | 'cancelled' | null;
          onboarding_completed?: boolean;
          demo_account?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      consent_records: {
        Row: {
          id: string;
          user_id: string;
          consent_id: string;
          consent_type: 'cookie' | 'dpdpa';
          status: 'accepted' | 'rejected' | 'partial' | 'revoked';
          categories: Json;
          device_type: 'Desktop' | 'Mobile' | 'Tablet';
          ip_address: string | null;
          user_agent: string | null;
          language: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          consent_id: string;
          consent_type: 'cookie' | 'dpdpa';
          status: 'accepted' | 'rejected' | 'partial' | 'revoked';
          categories: Json;
          device_type: 'Desktop' | 'Mobile' | 'Tablet';
          ip_address?: string | null;
          user_agent?: string | null;
          language?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          consent_id?: string;
          consent_type?: 'cookie' | 'dpdpa';
          status?: 'accepted' | 'rejected' | 'partial' | 'revoked';
          categories?: Json;
          device_type?: 'Desktop' | 'Mobile' | 'Tablet';
          ip_address?: string | null;
          user_agent?: string | null;
          language?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      consent_logs: {
        Row: {
          id: string;
          user_id: string;
          consent_id: string;
          visitor_token: string;
          widget_id: string | null;
          consent_type: 'cookie' | 'dpdpa' | 'gdpr';
          status: 'accepted' | 'rejected' | 'partial' | 'revoked' | 'updated';
          categories: string[];
          cookies_accepted: string[] | null;
          cookies_rejected: string[] | null;
          device_info: Json | null;
          geo_location: Json | null;
          ip_address: string | null;
          user_agent: string | null;
          referrer: string | null;
          page_url: string | null;
          language: string;
          browser_fingerprint: string | null;
          consent_method: 'banner' | 'settings_modal' | 'api' | 'implicit';
          widget_version: string | null;
          tcf_string: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          consent_id: string;
          visitor_token: string;
          widget_id?: string | null;
          consent_type: 'cookie' | 'dpdpa' | 'gdpr';
          status: 'accepted' | 'rejected' | 'partial' | 'revoked' | 'updated';
          categories?: string[];
          cookies_accepted?: string[] | null;
          cookies_rejected?: string[] | null;
          device_info?: Json | null;
          geo_location?: Json | null;
          ip_address?: string | null;
          user_agent?: string | null;
          referrer?: string | null;
          page_url?: string | null;
          language?: string;
          browser_fingerprint?: string | null;
          consent_method?: 'banner' | 'settings_modal' | 'api' | 'implicit';
          widget_version?: string | null;
          tcf_string?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          consent_id?: string;
          visitor_token?: string;
          widget_id?: string | null;
          consent_type?: 'cookie' | 'dpdpa' | 'gdpr';
          status?: 'accepted' | 'rejected' | 'partial' | 'revoked' | 'updated';
          categories?: string[];
          cookies_accepted?: string[] | null;
          cookies_rejected?: string[] | null;
          device_info?: Json | null;
          geo_location?: Json | null;
          ip_address?: string | null;
          user_agent?: string | null;
          referrer?: string | null;
          page_url?: string | null;
          language?: string;
          browser_fingerprint?: string | null;
          consent_method?: 'banner' | 'settings_modal' | 'api' | 'implicit';
          widget_version?: string | null;
          tcf_string?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      cookie_scans: {
        Row: {
          id: string;
          user_id: string;
          website_url: string;
          scan_date: string;
          cookies_found: Json;
          classification: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          website_url: string;
          scan_date?: string;
          cookies_found: Json;
          classification: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          website_url?: string;
          scan_date?: string;
          cookies_found?: Json;
          classification?: Json;
          created_at?: string;
        };
      };
      processing_activities: {
        Row: {
          id: string;
          user_id: string;
          activity_name: string;
          industry: string;
          data_attributes: string[]; // DEPRECATED: Use purpose_data_categories instead
          purpose: string; // DEPRECATED: Use activity_purposes instead
          retention_period: string; // DEPRECATED: Use purpose_data_categories instead
          data_processors: Json;
          legal_basis: 'consent' | 'contract' | 'legal-obligation' | 'legitimate-interest' | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          activity_name: string;
          industry: string;
          data_attributes?: string[];
          purpose?: string;
          retention_period?: string;
          data_processors?: Json;
          legal_basis?: 'consent' | 'contract' | 'legal-obligation' | 'legitimate-interest' | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          activity_name?: string;
          industry?: string;
          data_attributes?: string[];
          purpose?: string;
          retention_period?: string;
          data_processors?: Json;
          legal_basis?: 'consent' | 'contract' | 'legal-obligation' | 'legitimate-interest' | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      purposes: {
        Row: {
          id: string;
          purpose_name: string;
          description: string | null;
          name: string | null;
          data_category: string | null;
          retention_period: string | null;
          is_predefined: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          purpose_name: string;
          description?: string | null;
          name?: string | null;
          data_category?: string | null;
          retention_period?: string | null;
          is_predefined?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          purpose_name?: string;
          description?: string | null;
          name?: string | null;
          data_category?: string | null;
          retention_period?: string | null;
          is_predefined?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      activity_purposes: {
        Row: {
          id: string;
          activity_id: string;
          purpose_id: string;
          legal_basis: 'consent' | 'contract' | 'legal-obligation' | 'legitimate-interest';
          custom_description: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          activity_id: string;
          purpose_id: string;
          legal_basis: 'consent' | 'contract' | 'legal-obligation' | 'legitimate-interest';
          custom_description?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          activity_id?: string;
          purpose_id?: string;
          legal_basis?: 'consent' | 'contract' | 'legal-obligation' | 'legitimate-interest';
          custom_description?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      purpose_data_categories: {
        Row: {
          id: string;
          activity_purpose_id: string;
          category_name: string;
          retention_period: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          activity_purpose_id: string;
          category_name: string;
          retention_period: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          activity_purpose_id?: string;
          category_name?: string;
          retention_period?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      data_sources: {
        Row: {
          id: string;
          activity_id: string;
          source_name: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          activity_id: string;
          source_name: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          activity_id?: string;
          source_name?: string;
          created_at?: string;
        };
      };
      data_recipients: {
        Row: {
          id: string;
          activity_id: string;
          recipient_name: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          activity_id: string;
          recipient_name: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          activity_id?: string;
          recipient_name?: string;
          created_at?: string;
        };
      };
      subscriptions: {
        Row: {
          id: string;
          user_id: string;
          plan: 'small' | 'medium' | 'enterprise';
          status: 'active' | 'inactive' | 'cancelled';
          amount: number;
          currency: string;
          billing_cycle: 'monthly' | 'yearly';
          payment_provider: 'razorpay' | 'stripe';
          payment_id: string | null;
          start_date: string;
          end_date: string | null;
          is_trial: boolean;
          trial_end: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          plan: 'small' | 'medium' | 'enterprise';
          status?: 'active' | 'inactive' | 'cancelled';
          amount: number;
          currency?: string;
          billing_cycle?: 'monthly' | 'yearly';
          payment_provider?: 'razorpay' | 'stripe';
          payment_id?: string | null;
          start_date?: string;
          end_date?: string | null;
          is_trial?: boolean;
          trial_end?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          plan?: 'small' | 'medium' | 'enterprise';
          status?: 'active' | 'inactive' | 'cancelled';
          amount?: number;
          currency?: string;
          billing_cycle?: 'monthly' | 'yearly';
          payment_provider?: 'razorpay' | 'stripe';
          payment_id?: string | null;
          start_date?: string;
          end_date?: string | null;
          is_trial?: boolean;
          trial_end?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      email_verification_otps: {
        Row: {
          id: string;
          email: string;
          email_hash: string;
          otp_code: string;
          visitor_id: string;
          widget_id: string;
          expires_at: string;
          verified: boolean;
          verified_at: string | null;
          attempts: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          email: string;
          email_hash: string;
          otp_code: string;
          visitor_id: string;
          widget_id: string;
          expires_at: string;
          verified?: boolean;
          verified_at?: string | null;
          attempts?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          email_hash?: string;
          otp_code?: string;
          visitor_id?: string;
          widget_id?: string;
          expires_at?: string;
          verified?: boolean;
          verified_at?: string | null;
          attempts?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      widget_configs: {
        Row: {
          id: string;
          user_id: string;
          widget_id: string;
          domain: string;
          categories: string[];
          behavior: 'implicit' | 'explicit' | 'optout';
          consent_duration: number;
          show_branding_link: boolean;
          block_scripts: boolean;
          respect_dnt: boolean;
          gdpr_applies: boolean;
          auto_block: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          widget_id: string;
          domain: string;
          categories?: string[];
          behavior?: 'implicit' | 'explicit' | 'optout';
          consent_duration?: number;
          show_branding_link?: boolean;
          block_scripts?: boolean;
          respect_dnt?: boolean;
          gdpr_applies?: boolean;
          auto_block?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          widget_id?: string;
          domain?: string;
          categories?: string[];
          behavior?: 'implicit' | 'explicit' | 'optout';
          consent_duration?: number;
          show_branding_link?: boolean;
          block_scripts?: boolean;
          respect_dnt?: boolean;
          gdpr_applies?: boolean;
          auto_block?: string[];
          created_at?: string;
          updated_at?: string;
        };
      };
      visitor_consent_preferences: {
        Row: {
          id: string;
          visitor_id: string;
          visitor_email_hash: string | null;
          widget_id: string;
          activity_id: string;
          consent_status: 'accepted' | 'rejected' | 'withdrawn';
          ip_address: string | null;
          user_agent: string | null;
          device_type: 'Desktop' | 'Mobile' | 'Tablet' | 'Unknown' | null;
          language: string | null;
          consent_given_at: string;
          last_updated: string;
          expires_at: string | null;
          consent_version: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          visitor_id: string;
          visitor_email_hash?: string | null;
          widget_id: string;
          activity_id: string;
          consent_status: 'accepted' | 'rejected' | 'withdrawn';
          ip_address?: string | null;
          user_agent?: string | null;
          device_type?: 'Desktop' | 'Mobile' | 'Tablet' | 'Unknown' | null;
          language?: string | null;
          consent_given_at?: string;
          last_updated?: string;
          expires_at?: string | null;
          consent_version?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          visitor_id?: string;
          visitor_email_hash?: string | null;
          widget_id?: string;
          activity_id?: string;
          consent_status?: 'accepted' | 'rejected' | 'withdrawn';
          ip_address?: string | null;
          user_agent?: string | null;
          device_type?: 'Desktop' | 'Mobile' | 'Tablet' | 'Unknown' | null;
          language?: string | null;
          consent_given_at?: string;
          last_updated?: string;
          expires_at?: string | null;
          consent_version?: string;
          created_at?: string;
        };
      };
      dpdp_rights_requests: {
        Row: {
          id: string;
          visitor_id: string;
          visitor_email: string;
          visitor_email_hash: string;
          visitor_name: string | null;
          visitor_phone: string | null;
          widget_id: string;
          request_type: 'access' | 'correction' | 'erasure' | 'grievance' | 'nomination';
          request_title: string;
          request_description: string;
          status: 'pending' | 'under_review' | 'in_progress' | 'completed' | 'rejected' | 'cancelled';
          admin_notes: string | null;
          response_message: string | null;
          rejection_reason: string | null;
          attachments: Json;
          response_attachments: Json;
          is_verified: boolean;
          verification_token: string | null;
          verification_code: string | null;
          verified_at: string | null;
          ip_address: string | null;
          user_agent: string | null;
          device_type: string | null;
          language: string;
          due_date: string | null;
          completed_at: string | null;
          resolved_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          visitor_id: string;
          visitor_email: string;
          visitor_email_hash: string;
          visitor_name?: string | null;
          visitor_phone?: string | null;
          widget_id: string;
          request_type: 'access' | 'correction' | 'erasure' | 'grievance' | 'nomination';
          request_title: string;
          request_description: string;
          status?: 'pending' | 'under_review' | 'in_progress' | 'completed' | 'rejected' | 'cancelled';
          admin_notes?: string | null;
          response_message?: string | null;
          rejection_reason?: string | null;
          attachments?: Json;
          response_attachments?: Json;
          is_verified?: boolean;
          verification_token?: string | null;
          verification_code?: string | null;
          verified_at?: string | null;
          ip_address?: string | null;
          user_agent?: string | null;
          device_type?: string | null;
          language?: string;
          due_date?: string | null;
          completed_at?: string | null;
          resolved_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          visitor_id?: string;
          visitor_email?: string;
          visitor_email_hash?: string;
          visitor_name?: string | null;
          visitor_phone?: string | null;
          widget_id?: string;
          request_type?: 'access' | 'correction' | 'erasure' | 'grievance' | 'nomination';
          request_title?: string;
          request_description?: string;
          status?: 'pending' | 'under_review' | 'in_progress' | 'completed' | 'rejected' | 'cancelled';
          admin_notes?: string | null;
          response_message?: string | null;
          rejection_reason?: string | null;
          attachments?: Json;
          response_attachments?: Json;
          is_verified?: boolean;
          verification_token?: string | null;
          verification_code?: string | null;
          verified_at?: string | null;
          ip_address?: string | null;
          user_agent?: string | null;
          device_type?: string | null;
          language?: string;
          due_date?: string | null;
          completed_at?: string | null;
          resolved_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      consent_history: {
        Row: {
          id: string;
          visitor_id: string;
          widget_id: string;
          activity_id: string;
          previous_status: 'accepted' | 'rejected' | 'withdrawn' | null;
          new_status: 'accepted' | 'rejected' | 'withdrawn';
          change_reason: string | null;
          change_source: 'privacy_centre' | 'widget' | 'admin' | 'system';
          ip_address: string | null;
          user_agent: string | null;
          device_type: string | null;
          language: string | null;
          consent_version: string;
          changed_at: string;
        };
        Insert: {
          id?: string;
          visitor_id: string;
          widget_id: string;
          activity_id: string;
          previous_status?: 'accepted' | 'rejected' | 'withdrawn' | null;
          new_status: 'accepted' | 'rejected' | 'withdrawn';
          change_reason?: string | null;
          change_source?: 'privacy_centre' | 'widget' | 'admin' | 'system';
          ip_address?: string | null;
          user_agent?: string | null;
          device_type?: string | null;
          language?: string | null;
          consent_version?: string;
          changed_at?: string;
        };
        Update: {
          id?: string;
          visitor_id?: string;
          widget_id?: string;
          activity_id?: string;
          previous_status?: 'accepted' | 'rejected' | 'withdrawn' | null;
          new_status?: 'accepted' | 'rejected' | 'withdrawn';
          change_reason?: string | null;
          change_source?: 'privacy_centre' | 'widget' | 'admin' | 'system';
          ip_address?: string | null;
          user_agent?: string | null;
          device_type?: string | null;
          language?: string | null;
          consent_version?: string;
          changed_at?: string;
        };
      };
      cookie_banners: {
        Row: {
          id: string;
          user_id: string;
          website_url: string;
          banner_style: 'minimal' | 'detailed' | 'floating' | 'sidebar';
          position: 'top' | 'bottom' | 'center' | 'bottom-left' | 'bottom-right';
          primary_color: string;
          text_color: string;
          background_color: string;
          title: string;
          message: string;
          accept_text: string;
          reject_text: string;
          settings_text: string;
          language: string;
          categories: Json;
          industry: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          website_url: string;
          banner_style: 'minimal' | 'detailed' | 'floating' | 'sidebar';
          position?: 'top' | 'bottom' | 'center' | 'bottom-left' | 'bottom-right';
          primary_color?: string;
          text_color?: string;
          background_color?: string;
          title: string;
          message: string;
          accept_text?: string;
          reject_text?: string;
          settings_text?: string;
          language?: string;
          categories?: Json;
          industry?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          website_url?: string;
          banner_style?: 'minimal' | 'detailed' | 'floating' | 'sidebar';
          position?: 'top' | 'bottom' | 'center' | 'bottom-left' | 'bottom-right';
          primary_color?: string;
          text_color?: string;
          background_color?: string;
          title?: string;
          message?: string;
          accept_text?: string;
          reject_text?: string;
          settings_text?: string;
          language?: string;
          categories?: Json;
          industry?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      dpdpa_widget_configs: {
        Row: {
          id: string;
          user_id: string;
          widget_id: string;
          name: string;
          domain: string;
          position: 'top' | 'bottom' | 'center' | 'bottom-left' | 'bottom-right' | 'modal';
          layout: 'modal' | 'slide-in' | 'banner';
          theme: Json;
          title: string | null;
          message: string | null;
          accept_button_text: string;
          reject_button_text: string;
          customize_button_text: string;
          selected_activities: string[];
          auto_show: boolean;
          show_after_delay: number;
          consent_duration: number;
          respect_dnt: boolean;
          require_explicit_consent: boolean;
          show_data_subjects_rights: boolean;
          language: string;
          supported_languages: string[];
          custom_translations: Json;
          enable_analytics: boolean;
          enable_audit_log: boolean;
          show_branding: boolean;
          custom_css: string | null;
          privacy_notice_version: string | null;
          privacy_notice_last_updated: string | null;
          requires_reconsent: boolean;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          widget_id: string;
          name: string;
          domain: string;
          position?: 'top' | 'bottom' | 'center' | 'bottom-left' | 'bottom-right' | 'modal';
          layout?: 'modal' | 'slide-in' | 'banner';
          theme?: Json;
          title?: string | null;
          message?: string | null;
          accept_button_text?: string;
          reject_button_text?: string;
          customize_button_text?: string;
          selected_activities?: string[];
          auto_show?: boolean;
          show_after_delay?: number;
          consent_duration?: number;
          respect_dnt?: boolean;
          require_explicit_consent?: boolean;
          show_data_subjects_rights?: boolean;
          language?: string;
          supported_languages?: string[];
          custom_translations?: Json;
          enable_analytics?: boolean;
          enable_audit_log?: boolean;
          show_branding?: boolean;
          custom_css?: string | null;
          privacy_notice_version?: string | null;
          privacy_notice_last_updated?: string | null;
          requires_reconsent?: boolean;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          widget_id?: string;
          name?: string;
          domain?: string;
          position?: 'top' | 'bottom' | 'center' | 'bottom-left' | 'bottom-right' | 'modal';
          layout?: 'modal' | 'slide-in' | 'banner';
          theme?: Json;
          title?: string | null;
          message?: string | null;
          accept_button_text?: string;
          reject_button_text?: string;
          customize_button_text?: string;
          selected_activities?: string[];
          auto_show?: boolean;
          show_after_delay?: number;
          consent_duration?: number;
          respect_dnt?: boolean;
          require_explicit_consent?: boolean;
          show_data_subjects_rights?: boolean;
          language?: string;
          supported_languages?: string[];
          custom_translations?: Json;
          enable_analytics?: boolean;
          enable_audit_log?: boolean;
          show_branding?: boolean;
          custom_css?: string | null;
          privacy_notice_version?: string | null;
          privacy_notice_last_updated?: string | null;
          requires_reconsent?: boolean;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      dpdpa_consent_records: {
        Row: {
          id: string;
          widget_id: string;
          visitor_id: string;
          consent_id: string;
          consent_status: 'accepted' | 'rejected' | 'partial' | 'revoked';
          consented_activities: string[];
          rejected_activities: string[];
          consent_details: Json;
          visitor_email_hash: string | null;
          user_agent: string | null;
          ip_address: string | null;
          device_type: string | null;
          browser: string | null;
          os: string | null;
          language: string | null;
          country_code: string | null;
          region: string | null;
          consent_given_at: string;
          consent_expires_at: string | null;
          revoked_at: string | null;
          revocation_reason: string | null;
          privacy_notice_version: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          widget_id: string;
          visitor_id: string;
          consent_id: string;
          consent_status: 'accepted' | 'rejected' | 'partial' | 'revoked';
          consented_activities?: string[];
          rejected_activities?: string[];
          consent_details?: Json;
          visitor_email_hash?: string | null;
          user_agent?: string | null;
          ip_address?: string | null;
          device_type?: string | null;
          browser?: string | null;
          os?: string | null;
          language?: string | null;
          country_code?: string | null;
          region?: string | null;
          consent_given_at?: string;
          consent_expires_at?: string | null;
          revoked_at?: string | null;
          revocation_reason?: string | null;
          privacy_notice_version?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          widget_id?: string;
          visitor_id?: string;
          consent_id?: string;
          consent_status?: 'accepted' | 'rejected' | 'partial' | 'revoked';
          consented_activities?: string[];
          rejected_activities?: string[];
          consent_details?: Json;
          visitor_email_hash?: string | null;
          user_agent?: string | null;
          ip_address?: string | null;
          device_type?: string | null;
          browser?: string | null;
          os?: string | null;
          language?: string | null;
          country_code?: string | null;
          region?: string | null;
          consent_given_at?: string;
          consent_expires_at?: string | null;
          revoked_at?: string | null;
          revocation_reason?: string | null;
          privacy_notice_version?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      dpdpa_grievances: {
        Row: {
          id: string;
          widget_id: string;
          visitor_id: string | null;
          email: string;
          full_name: string | null;
          phone: string | null;
          request_type: 'access' | 'correction' | 'erasure' | 'withdrawal' | 'portability' | 'grievance' | 'other';
          subject: string;
          description: string;
          status: 'pending' | 'in_progress' | 'resolved' | 'rejected' | 'escalated';
          priority: 'low' | 'medium' | 'high' | 'urgent';
          resolved_at: string | null;
          resolved_by: string | null;
          resolution_notes: string | null;
          response_due_at: string | null;
          first_response_at: string | null;
          assigned_to: string | null;
          internal_notes: string | null;
          attachments: Json;
          compliance_status: 'pending' | 'compliant' | 'overdue' | 'breached';
          escalation_reason: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          widget_id: string;
          visitor_id?: string | null;
          email: string;
          full_name?: string | null;
          phone?: string | null;
          request_type: 'access' | 'correction' | 'erasure' | 'withdrawal' | 'portability' | 'grievance' | 'other';
          subject: string;
          description: string;
          status?: 'pending' | 'in_progress' | 'resolved' | 'rejected' | 'escalated';
          priority?: 'low' | 'medium' | 'high' | 'urgent';
          resolved_at?: string | null;
          resolved_by?: string | null;
          resolution_notes?: string | null;
          response_due_at?: string | null;
          first_response_at?: string | null;
          assigned_to?: string | null;
          internal_notes?: string | null;
          attachments?: Json;
          compliance_status?: 'pending' | 'compliant' | 'overdue' | 'breached';
          escalation_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          widget_id?: string;
          visitor_id?: string | null;
          email?: string;
          full_name?: string | null;
          phone?: string | null;
          request_type?: 'access' | 'correction' | 'erasure' | 'withdrawal' | 'portability' | 'grievance' | 'other';
          subject?: string;
          description?: string;
          status?: 'pending' | 'in_progress' | 'resolved' | 'rejected' | 'escalated';
          priority?: 'low' | 'medium' | 'high' | 'urgent';
          resolved_at?: string | null;
          resolved_by?: string | null;
          resolution_notes?: string | null;
          response_due_at?: string | null;
          first_response_at?: string | null;
          assigned_to?: string | null;
          internal_notes?: string | null;
          attachments?: Json;
          compliance_status?: 'pending' | 'compliant' | 'overdue' | 'breached';
          escalation_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
}
