import { NextRequest, NextResponse } from 'next/server';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { activities, domain, companyName } = body;

    const doc = new jsPDF();
    const margin = 20;
    let currentY = 20;

    // Header
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(37, 99, 235);
    doc.text('Privacy Notice', margin, currentY);
    currentY += 10;

    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 116, 139);
    doc.text(`Domain: ${domain || 'N/A'}`, margin, currentY);
    currentY += 6;
    doc.text(`Date: ${new Date().toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' })}`, margin, currentY);
    currentY += 15;

    // Introduction
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(31, 41, 55);
    doc.text('Introduction', margin, currentY);
    currentY += 8;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(75, 85, 99);
    const introText = `This Privacy Notice is provided by ${companyName || domain || 'us'} in compliance with the Digital Personal Data Protection Act, 2023 (India). It explains how we collect, use, and protect your personal data.`;
    const introLines = doc.splitTextToSize(introText, 170);
    doc.text(introLines, margin, currentY);
    currentY += (introLines.length * 5) + 10;

    // Processing Activities
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(31, 41, 55);
    doc.text('Data Processing Activities', margin, currentY);
    currentY += 5;

    if (activities && activities.length > 0) {
      const tableData = activities.map((activity: any) => {
        let purposes = 'N/A';
        let dataCategories = 'N/A';

        if (activity.purposes && Array.isArray(activity.purposes)) {
          purposes = activity.purposes.map((p: any) => p.purposeName).join(', ');
          const cats = new Set();
          activity.purposes.forEach((p: any) => {
            if (p.dataCategories) {
              p.dataCategories.forEach((c: any) => cats.add(c.categoryName));
            }
          });
          dataCategories = Array.from(cats).join(', ');
        } else if (activity.data_attributes) {
          dataCategories = activity.data_attributes.join(', ');
          purposes = activity.activity_description || 'N/A';
        }

        return [activity.activity_name, purposes, dataCategories];
      });

      autoTable(doc, {
        startY: currentY,
        head: [['Activity', 'Purpose', 'Data Categories']],
        body: tableData,
        theme: 'grid',
        headStyles: { fillColor: [37, 99, 235], textColor: [255, 255, 255] },
        margin: { left: margin, right: margin },
      });
      currentY = (doc as any).lastAutoTable.finalY + 15;
    }

    // Rights Section
    if (currentY + 60 > doc.internal.pageSize.height) {
      doc.addPage();
      currentY = 20;
    }

    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(31, 41, 55);
    doc.text('Your Rights Under DPDPA 2023', margin, currentY);
    currentY += 8;

    const rights = [
      ['Right to Access', 'Request information about what personal data we hold about you.'],
      ['Right to Correction', 'Request correction of inaccurate or incomplete data.'],
      ['Right to Erasure', 'Request deletion of your personal data in certain circumstances.'],
      ['Right to Withdraw', 'Withdraw your consent at any time.'],
      ['Grievance Redressal', 'Raise a grievance with our Data Protection Officer.'],
    ];

    autoTable(doc, {
      startY: currentY,
      body: rights,
      theme: 'plain',
      columnStyles: {
        0: { fontStyle: 'bold', cellWidth: 40 },
        1: { cellWidth: 130 }
      },
      margin: { left: margin },
    });
    currentY = (doc as any).lastAutoTable.finalY + 20;

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(156, 163, 175);
    const footerText = 'Generated by Consently - DPDPA Compliance Platform (consently.in)';
    doc.text(footerText, doc.internal.pageSize.width / 2, doc.internal.pageSize.height - 10, { align: 'center' });

    const pdfBuffer = Buffer.from(doc.output('arraybuffer'));

    return new NextResponse(pdfBuffer, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="privacy-notice-${domain || 'notice'}.pdf"`,
      },
    });
  } catch (error) {
    console.error('Privacy Notice PDF Generation Error:', error);
    return NextResponse.json({ error: 'Failed to generate PDF' }, { status: 500 });
  }
}
