// Common data categories for different types of processing activities
export const COMMON_DATA_CATEGORIES = [
  // Personal Identifiers
  'Email',
  'Name',
  'Full Name',
  'First Name',
  'Last Name',
  'Phone Number',
  'Mobile Number',
  'Date of Birth',
  'Age',
  'Gender',
  'Address',
  'City',
  'State',
  'Country',
  'Postal Code',
  'ZIP Code',
  
  // Identity Documents
  'Passport Number',
  'Driver License',
  'National ID',
  'PAN Card',
  'Aadhaar Number',
  'Social Security Number',
  'Tax ID',
  'Voter ID',
  
  // Account & Authentication
  'Username',
  'Password Hash',
  'Security Questions',
  'Two-Factor Authentication',
  'Account ID',
  'User ID',
  'Customer ID',
  'Session Token',
  
  // Financial Information
  'Payment Method',
  'Credit Card Number',
  'Card Last 4 Digits',
  'Bank Account Number',
  'IFSC Code',
  'Transaction ID',
  'Payment History',
  'Billing Address',
  'Invoice Details',
  'Credit Score',
  'Income Details',
  'Salary Information',
  
  // Employment & Education
  'Employment Information',
  'Employer Name',
  'Job Title',
  'Work Email',
  'Company Name',
  'Student ID',
  'Education Records',
  'Academic Records',
  
  // Medical & Health
  'Medical History',
  'Health Records',
  'Prescription Details',
  'Test Results',
  'Blood Type',
  'Allergies',
  'Medical Conditions',
  'Insurance Details',
  
  // Location & Device
  'IP Address',
  'Location Data',
  'GPS Coordinates',
  'Device Information',
  'Device ID',
  'Browser Information',
  'Operating System',
  'MAC Address',
  
  // Behavioral & Usage
  'Browsing History',
  'Purchase History',
  'Search History',
  'Click Data',
  'Page Views',
  'Session Duration',
  'User Preferences',
  'Communication Preferences',
  
  // Biometric Data
  'Biometric Data',
  'Fingerprint',
  'Face Recognition',
  'Voice Recording',
  'Signature',
  'Photograph',
  
  // Communication Data
  'Email Content',
  'Chat Messages',
  'Call Recordings',
  'SMS Messages',
  'Communication History',
  'Support Tickets',
  'Feedback',
  'Reviews',
  'Ratings',
  
  // Social Media
  'Social Media Profile',
  'Profile Picture',
  'Posts',
  'Comments',
  'Likes',
  'Shares',
  'Friends List',
  
  // Property & Assets
  'Property Details',
  'Vehicle Number',
  'Asset Information',
  'Ownership Records',
  
  // Cookies & Tracking
  'Cookies',
  'Tracking Pixels',
  'Analytics Data',
  'Marketing Data',
  'Advertising ID',
];

export const DATA_SOURCES_SUGGESTIONS = [
  'Website',
  'Mobile App',
  'Web Application',
  'Registration Form',
  'Contact Form',
  'Checkout Form',
  'API',
  'Third-party APIs',
  'Social Login APIs',
  'Payment Gateway',
  'CRM System',
  'Database',
  'Email Service',
  'SMS Gateway',
  'Customer Support Portal',
  'Live Chat System',
  'Analytics Tools',
  'Marketing Platform',
  'Call Center',
  'In-person Collection',
  'Document Upload',
  'Biometric Scanner',
  'Video Conferencing',
  'IoT Devices',
];

export const DATA_RECIPIENTS_SUGGESTIONS = [
  'Internal Teams',
  'IT Department',
  'Marketing Team',
  'Sales Team',
  'Customer Support',
  'Analytics Providers',
  'Cloud Storage Providers',
  'Payment Processors',
  'Email Service Providers',
  'SMS Providers',
  'Advertising Networks',
  'Social Media Platforms',
  'Government Authorities',
  'Legal Advisors',
  'Auditors',
  'Business Partners',
  'Service Providers',
  'Data Processors',
  'Third-party Vendors',
];
