-- Migration to add DPDPA blog posts

INSERT INTO public.blog_posts (
  title,
  slug,
  excerpt,
  content,
  category,
  tags,
  author_name,
  author_email,
  published,
  published_at,
  reading_time,
  meta_title,
  meta_description,
  seo_keywords
)
VALUES
(
  'DPDPA Compliance Timeline Reduced by MEITY',
  'dpdpa-compliance-timeline-reduced-meity',
  'The Ministry of Electronics and Information Technology (MEITY) has signaled a faster implementation of the DPDPA 2023 rules. Businesses need to act now.',
  '<h2>Urgent Update for Indian Businesses</h2><p>The Ministry of Electronics and Information Technology (MEITY) has indicated a reduced timeline for the full enforcement of the Digital Personal Data Protection Act (DPDPA) 2023. Originally expected to allow a longer grace period, recent announcements suggest that businesses will need to demonstrate compliance much sooner than anticipated.</p><h3>What This Means for You</h3><p>If you have been delaying your compliance journey, the window of opportunity is closing. The "wait and see" approach is no longer viable. Key requirements such as Consent Management, Data Fiduciary obligations, and Grievance Redressal mechanisms must be in place.</p><h3>Key Deadlines to Watch</h3><ul><li><strong>Consent Manager Registration:</strong> Expected to open soon.</li><li><strong>Data Fiduciary Reporting:</strong> Timelines likely shortened to 3-6 months post-notification.</li></ul><p>Start your compliance journey today to avoid penalties that can reach up to ₹250 Crores.</p>',
  'News',
  ARRAY['DPDPA', 'MEITY', 'Compliance', 'Regulations'],
  'Consently Team',
  'hello@consently.in',
  true,
  NOW() - INTERVAL '2 days',
  3,
  'DPDPA Compliance Timeline Reduced by MEITY - Urgent Update',
  'MEITY has reduced the DPDPA compliance timeline. Learn what this urgent update means for your business and how to avoid penalties.',
  ARRAY['DPDPA compliance timeline', 'MEITY data protection notification', 'DPDP Act enforcement date']
),
(
  'How Consently.in Can Help Achieve Organisation Compliance in 3 Months',
  'achieve-dpdpa-compliance-in-3-months',
  'A strategic roadmap combining expert consulting with our powerful automation tools to get you audit-ready in just 90 days.',
  '<h2>The 90-Day Compliance Roadmap</h2><p>Achieving DPDPA compliance doesn''t have to be a multi-year ordeal. With the right combination of <strong>consulting expertise</strong> and <strong>automation tools</strong>, your organization can be fully compliant in just 3 months.</p><h3>Month 1: Assessment & Discovery</h3><p>We start by mapping your data. Our consultants work with you to identify:</p><ul><li>Where personal data enters your organization (Data Ingestion)</li><li>Where it is stored and processed (Data Flow)</li><li>Who has access to it (Access Control)</li></ul><p>Simultaneously, we deploy the <strong>Consently Cookie Scanner</strong> to audit your public-facing digital properties.</p><h3>Month 2: Implementation & Integration</h3><p>This is where the magic happens. We implement:</p><ul><li><strong>Consent Managers:</strong> Deploy Consently''s granular consent widgets across web and mobile.</li><li><strong>Policy Frameworks:</strong> Draft and publish privacy notices compliant with Section 5 of the Act.</li><li><strong>Data Subject Rights (DSR) Portal:</strong> automated workflows for handling access and erasure requests.</li></ul><h3>Month 3: Assurance & Training</h3><p>The final lap involves:</p><ul><li><strong>Mock Audits:</strong> We simulate a Data Protection Board audit to find gaps.</li><li><strong>Employee Training:</strong> Sensitizing your staff to data privacy principles.</li><li><strong>Go-Live:</strong> Full certification of compliance.</li></ul><p><a href="/consulting">Contact us today</a> to start your 3-month journey.</p>',
  'Strategy',
  ARRAY['Compliance Strategy', 'Consulting', 'Roadmap'],
  'Consently Team',
  'hello@consently.in',
  true,
  NOW() - INTERVAL '1 day',
  5,
  'DPDPA Compliance in 3 Months - Consulting + Tools',
  'Get DPDPA compliaint in 3 months with Consently. Our unique Consulting + Tools approach ensures you are audit-ready fast.',
  ARRAY['best consent management platforms in india', 'automate cookie scanning dpdpa', 'dpdpa consulting services']
),
(
  'DPDPA Compliance for Hospitality Sector',
  'dpdpa-compliance-hospitality-sector',
  'Hotels and travel businesses process vast amounts of sensitive guest data. Here is how to handle check-ins, loyalty programs, and bookings legally.',
  '<h2>Data Privacy in Hospitality</h2><p>The hospitality sector is unique. You collect data at every touchpoint: booking, check-in, wifi login, spa reservations, and dining. Under DPDPA 2023, every single one of these interactions requires a valid <strong>Legal Basis</strong>, usually Consent.</p><h3>Key Challenges</h3><ul><li><strong>Guest Profiles:</strong> Storing passport copies and ID proofs requires strict security measures.</li><li><strong>Cross-Border Transfers:</strong> International hotel chains must ensure data stored abroad meets adequacy norms.</li><li><strong>Marketing:</strong> You cannot reuse check-in data for email marketing without explicit opt-in.</li></ul><h3>The Consently Solution</h3><p>Use our <strong>Purpose-Specific Consent</strong> modules to capture distinct consents for "Room Service" vs "Marketing Offers". Ensure your front-desk software is integrated with a Consent Manager.</p>',
  'Sector Guides',
  ARRAY['Hospitality', 'Hotels', 'Travel'],
  'Consently Team',
  'hello@consently.in',
  true,
  NOW(),
  4,
  'DPDPA Compliance for Hospitality Sector | Hotel Data Privacy',
  'Learn how the hospitality sector can comply with DPDPA 2023. Managing guest data, check-ins, and loyalty programs legally.',
  ARRAY['DPDPA compliance for Hospitality Sector', 'hotel data privacy india', 'guest consent management']
),
(
  'DPDPA Compliance for Real Estate Sector',
  'dpdpa-compliance-real-estate-sector',
  'Real estate developers dealing with HNI data and property inquiries face strict scrutiny. Learn how to manage lead data compliantly.',
  '<h2>Protecting Property Buyer Data</h2><p>Real estate transactions involve high-value individuals and sensitive financial data. The common practice of sharing "lead lists" with brokers and agents is now a major risk under DPDPA.</p><h3>Stop the Leakage</h3><p>You are responsible for the data you collect. If a channel partner misuses your lead data, <strong>you</strong> (the Data Fiduciary) are liable.</p><h3>Compliance Steps</h3><ol><li><strong>Vendor Risk Management:</strong> Sign rigorous Data Processing Agreements (DPAs) with all brokers.</li><li><strong>Lead Capture Consent:</strong> Every inquiry form on your website must have a clear consent checkbox.</li><li><strong>Data Minimization:</strong> Don''t collect PAN cards or financial details until the booking stage.</li></ol>',
  'Sector Guides',
  ARRAY['Real Estate', 'Property', 'Leads'],
  'Consently Team',
  'hello@consently.in',
  true,
  NOW(),
  4,
  'DPDPA Compliance for Real Estate Sector | Lead Management',
  'Real estate data privacy guide. How to manage property leads and HNI data under India''s DPDPA 2023 laws.',
  ARRAY['DPDPA compliance for Real Estate Sector', 'real estate data protection compliance', 'property lead consent']
),
(
  'DPDPA Compliance for Banking/NBFC Sector',
  'dpdpa-compliance-banking-nbfc-sector',
  'Financial institutions are heavily regulated. DPDPA adds another layer of compliance for customer data protection and consent.',
  '<h2>Trust is Your Currency</h2><p>Banks and NBFCs are already regulated by RBI, but DPDPA 2023 introduces specific requirements for digital consent that go beyond standard KYC.</p><h3>Consent Architecture</h3><p>The "bundled consent" in 50-page loan agreements is no longer valid. You need <strong>granular consent</strong> for:</p><ul><li>Credit Bureau checks</li><li>Marketing SMS/Calls</li><li>Sharing data with insurance partners</li><li>Co-branded card offers</li></ul><h3>Consent Manager Framework</h3><p>Banks must integrate with the new Account Aggregator and Consent Manager frameworks to allow users to view and revoke consent via a single dashboard.</p>',
  'Sector Guides',
  ARRAY['Banking', 'NBFC', 'Finance', 'Fintech'],
  'Consently Team',
  'hello@consently.in',
  true,
  NOW(),
  6,
  'DPDPA Compliance for Banking & NBFCs | Financial Data Privacy',
  'A guide for Banks and NBFCs on DPDPA compliance. Managing granular consent for credit checks, marketing, and third-party sharing.',
  ARRAY['DPDPA compliance for Banking/NBFC Sector', 'fintech data privacy india', 'rbi vs dpdpa compliance']
),
(
  'DPDPA Compliance for Healthcare Sector',
  'dpdpa-compliance-healthcare-sector',
  'Health data is highly sensitive. Hospitals and diagnostic chains must implement robust consent and security protocols.',
  '<h2>Patient Confidentiality & Data Protection</h2><p>Health data falls under strict protection norms. DPDPA mandates that Data Fiduciaries in healthcare implement "reasonable security safeguards" to prevent breaches.</p><h3>Digital Health Records</h3><p>With the push for ABHA (Ayushman Bharat Health Account), digital records are increasing. You must ensure:</p><ul><li><strong>Purpose Limitation:</strong> Data collected for diagnosis cannot be used for research without fresh consent.</li><li><strong>Parental Consent:</strong> Processing data of minors requires verifiable parental consent.</li></ul><p>Consently offers specialized <strong>Healthcare Consent Templates</strong> designed for hospitals and clinics.</p>',
  'Sector Guides',
  ARRAY['Healthcare', 'Hospitals', 'Medical Data'],
  'Consently Team',
  'hello@consently.in',
  true,
  NOW(),
  5,
  'DPDPA Compliance for Healthcare Sector | Patient Data Privacy',
  'Healthcare data protection guide under DPDPA. Managing patient consent, digital health records, and minor data.',
  ARRAY['DPDPA compliance for Healthcare Sector', 'health data privacy india', 'hospital consent management']
),
(
  'DPDPA Compliance for SaaS Companies',
  'dpdpa-compliance-saas-companies',
  'B2B and B2C SaaS platforms must manage user consent for data processing, cookies, and third-party integrations.',
  '<h2>SaaS: The Data Processors & Fiduciaries</h2><p>SaaS companies often act as both Data Fiduciaries (for their own user data) and Data Processors (for their clients'' data).</p><h3>Key Responsibilities</h3><ul><li><strong>Cookie Compliance:</strong> Your marketing site and app interface likely use analytics cookies. These need explicit consent.</li><li><strong>Product Analytics:</strong> Tracking user behavior (Heatmaps, Session Recording) falls under personal data monitoring.</li><li><strong>Sub-processors:</strong> You must disclose all third-party vendors (AWS, Stripe, Twilio) you use to your customers.</li></ul><p><strong>Consently for SaaS</strong> automates this entire chain, providing a unified compliance dashboard.</p>',
  'Sector Guides',
  ARRAY['SaaS', 'Technology', 'B2B'],
  'Consently Team',
  'hello@consently.in',
  true,
  NOW(),
  5,
  'DPDPA Compliance for SaaS Companies | Software Data Privacy',
  'Guide for SaaS companies on DPDPA 2023. Handle user consent, cookies, and sub-processor disclosures correctly.',
  ARRAY['DPDPA compliance for SaaS Companies', 'saas data privacy india', 'cookie consent for saas']
),
(
  'DPDPA Compliance for Manufacturing Companies',
  'dpdpa-compliance-manufacturing-companies',
  'Compliance isn''t just for tech companies. Factories must protect employee data, vendor details, and supply chain information.',
  '<h2>Employee Data is Personal Data</h2><p>Manufacturing units employ thousands of workers, often on contract. Their biometrics, bank details, and family information are personal data.</p><h3>Workforce Management</h3><ul><li><strong>Biometric Attendance:</strong> Needs specific consent and secure storage.</li><li><strong>Payroll Processing:</strong> Sharing data with outsourced payroll vendors requires a Data Processing Agreement.</li></ul><h3>Vendor Data</h3><p>Details of sole proprietorship vendors may also count as personal data. Ensure your vendor onboarding forms include privacy notices.</p>',
  'Sector Guides',
  ARRAY['Manufacturing', 'Supply Chain', 'HR'],
  'Consently Team',
  'hello@consently.in',
  true,
  NOW(),
  4,
  'DPDPA Compliance for Manufacturing Sector | Employee Data',
  'Manufacturing sector DPDPA guide. Learn to protect employee biometrics, payroll data, and vendor information.',
  ARRAY['DPDPA compliance for Manufacturing Companies', 'employee data protection india', 'biometric consent manufacturing']
),
(
  'DPDPA Compliance for Tourism Sector',
  'dpdpa-compliance-tourism-sector',
  'Travel agencies and tour operators handle passports, visas, and itinerary data. Learn how to secure traveler information.',
  '<h2>Securing the Traveler''s Journey</h2><p>Tourism involves massive data sharing: you collect data from a customer and share it with airlines, hotels, visa consulates, and local guides.</p><h3>The Chain of Responsibility</h3><p>Every time you share a passport copy with a local vendor in another city, you are exposing data. DPDPA requires you to ensure that these "Data Processors" are compliant.</p><h3>Consent for Visa Processing</h3><p>Explicitly ask for consent to share data with embassies and visa processing centers. Do not retain passport copies longer than necessary for the trip.</p>',
  'Sector Guides',
  ARRAY['Tourism', 'Travel Agencies', 'Visa'],
  'Consently Team',
  'hello@consently.in',
  true,
  NOW(),
  4,
  'DPDPA Compliance for Tourism Sector | Travel Agency Guide',
  'Tourism sector guide for DPDPA 2023. Handling passport data, visa processing, and vendor data sharing.',
  ARRAY['DPDPA compliance for tourism sector', 'travel agency data privacy', 'passport data protection']
),
(
  'DPDPA Compliance for E-commerce Retail Companies',
  'dpdpa-compliance-ecommerce-retail',
  'E-commerce platforms rely on user data for personalization. Balancing conversion rates with compliance is the key challenge.',
  '<h2>Personalization vs Privacy</h2><p>E-commerce thrives on knowing the customer. Recommendation engines, cart recovery emails, and retargeting ads all use personal data.</p><h3>The "Dark Patterns" Trap</h3><p>DPDPA explicitly forbids "Dark Patterns" — UI designs that trick users into consenting. For example:</p><ul><li>Pre-ticked "Subscribe to Newsletter" boxes are banned.</li><li>Forcing a user to create an account just to browse is risky.</li></ul><h3>Checkout Consent</h3><p>Integrate consent checkboxes seamlessly into your checkout flow. Ensure "Legitimate Interest" covers transactional updates, but get consent for promotional ones.</p>',
  'Sector Guides',
  ARRAY['Ecommerce', 'Retail', 'Online Shopping'],
  'Consently Team',
  'hello@consently.in',
  true,
  NOW(),
  5,
  'DPDPA Compliance for E-commerce | Online Retail Privacy',
  'E-commerce private guide. How to balance personalization with DPDPA compliance, avoid dark patterns, and handle checkout consent.',
  ARRAY['DPDPA compliance for e-commerce retail companies', 'ecommerce data privacy india', 'no dark patterns']
),
(
  'DPDPA Compliance for Retail Sector',
  'dpdpa-compliance-retail-sector',
  'Offline retail stores collecting phone numbers at billing counters need to be careful. The digital law applies to digitized offline data too.',
  '<h2>The Billing Counter Dilemma</h2><p>We''ve all seen it: "Sir, what is your phone number?" at the cash counter. Retailers often make this mandatory for billing.</p><h3>Is it Legal?</h3><p>Under DPDPA, you cannot deny a service (selling a product) just because a user refuses to give consent for non-necessary data. A phone number is NOT necessary to sell a shirt for cash.</p><h3>Digital Receipts</h3><p>If you collect numbers for digital receipts, you must effectively limit usage to just sending the receipt, unless the user explicitly opts in for loyalty marketing.</p>',
  'Sector Guides',
  ARRAY['Retail', 'Offline Retail', 'POS'],
  'Consently Team',
  'hello@consently.in',
  true,
  NOW(),
  4,
  'DPDP Compliance for Retail Sector | POS Data Collection',
  'Retail sector guide. Rules for collecting phone numbers at billing counters and managing loyalty program data under DPDPA.',
  ARRAY['DPDP compliance for Retail Sector', 'retail billing phone number rules', 'pos data privacy']
);
